name: NFCRelay
options:
  bundleIdPrefix: com.example
targets:
  NFCRelay:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: NFCRelay
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: NFCRelay/NFCRelay.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.example.NFCRelay
        INFOPLIST_FILE: NFCRelay/Info.plist
        SWIFT_VERSION: "6.0"
    dependencies:
      - package: CieSDK
packages:
  CieSDK:
    url: https://github.com/pagopa/cie-sdk-ios
    branch: main
